#!/usr/bin/env python3
"""Apply precise Quranic evidence mapping — removes round-robin ayah assignment."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SEED_PATH = ROOT / "src/data/seed_content.json"
PRECISE_PATH = ROOT / "src/data/precise_event_evidence.json"
REPORT_PATH = ROOT / "docs/evidence_mapping_report.md"

seed = json.loads(SEED_PATH.read_text(encoding="utf-8"))
precise_file = json.loads(PRECISE_PATH.read_text(encoding="utf-8"))
mappings = {m["event_id"]: m for m in precise_file["mappings"]}

events = seed["story_events"]
before_count = len(events)
approved_before = [e for e in events if e.get("review_status") == "approved"]

downgraded = []
precise_events = []
needs_mapping = []
new_event_ayahs = []

for event in events:
    eid = event["id"]
    mapping = mappings.get(eid)

    if mapping:
        event["evidence_status"] = "precise_evidence"
        event["evidence_confidence"] = mapping["evidence_confidence"]
        event["review_status"] = mapping["review_status"]
        event["source_status"] = mapping["source_status"]

        if event.get("review_status") == "approved" and eid not in [x["id"] for x in approved_before if x["id"] == eid]:
            pass

        was_approved = eid in {e["id"] for e in approved_before}
        if was_approved and mapping["review_status"] != "approved":
            downgraded.append(eid)

        ayah_key = f"{mapping['surah_id']}:{mapping['ayah_from']}"
        if mapping["ayah_to"] != mapping["ayah_from"]:
            ayah_key += f"-{mapping['ayah_to']}"

        new_event_ayahs.append({
            "event_id": eid,
            "surah_id": mapping["surah_id"],
            "ayah_from": mapping["ayah_from"],
            "ayah_to": mapping["ayah_to"],
            "ayah_key": ayah_key,
            "relation_type": mapping["relation_type"],
            "evidence_note_ar": mapping["evidence_note_ar"],
            "note_ar": mapping["evidence_note_ar"],
        })

        if mapping["review_status"] == "approved" and mapping["evidence_confidence"] != "needs_review":
            precise_events.append(eid)
        else:
            precise_events.append(eid)
    else:
        prev_approved = event.get("review_status") == "approved"
        event["evidence_status"] = "needs_precise_mapping"
        event["evidence_confidence"] = "needs_review"
        event["review_status"] = "pending"
        event["source_status"] = event.get("source_status") if event.get("source_status") in ("pending", "needs_source", "none") else "pending"
        if prev_approved:
            downgraded.append(eid)
        needs_mapping.append(eid)

# Track downgrades from approved due to round-robin fix (musa_firawn etc.)
for e in approved_before:
    if e["id"] not in mappings and e["id"] not in downgraded:
        downgraded.append(e["id"])

seed["story_events"] = events
seed["event_ayahs"] = new_event_ayahs
seed["meta"]["version"] = "0.4.0"
seed["meta"]["evidence_policy"] = "Round-robin ayah assignment removed. Only curated precise_event_evidence.json mappings are trusted."

SEED_PATH.write_text(json.dumps(seed, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

safe_public = [
    e for e in events
    if e.get("review_status") == "approved"
    and e.get("source_status") not in ("none", "needs_source")
    and e.get("evidence_status") == "precise_evidence"
    and e.get("evidence_confidence") != "needs_review"
]

report = f"""# Evidence Mapping Report — Phase 5

**Date:** Generated by `scripts/apply_precise_evidence.py`  
**Seed version:** {seed['meta']['version']}  
**Curated mappings file:** `src/data/precise_event_evidence.json`

---

## Summary

| Metric | Count |
|--------|------:|
| Events before mapping review | {before_count} |
| Events with `precise_evidence` | {len([e for e in events if e.get('evidence_status') == 'precise_evidence'])} |
| Events with `needs_precise_mapping` | {len(needs_mapping)} |
| Approved before Phase 5 | {len(approved_before)} |
| Downgraded from approved → pending | {len(set(downgraded))} |
| Safe for public final display | {len(safe_public)} |

---

## Why approximate mapping was removed

Phase 3A migration used **round-robin** assignment (`parsed_ayahs[(i - 1) % len(parsed_ayahs)]`) to attach prototype figure-level ayah blocks to every event. This caused:

- The same ayah key on multiple events (e.g. `71:5-20` on both nuh dawah and ark)
- Wrong ayahs on approved events (e.g. `muhammad_revelation` with `33:40` instead of `96:1-5`)
- False impression of per-event scholarly verification

**Policy now:** Only events in `precise_event_evidence.json` receive ayah rows. All others are `needs_precise_mapping` with **no** ayah reference.

---

## Downgraded from approved

{chr(10).join(f'- `{eid}`' for eid in sorted(set(downgraded))) if downgraded else '- None'}

---

## Events with precise evidence (curated)

| event_id | review_status | evidence_confidence | ayah |
|----------|---------------|---------------------|------|
"""
for m in precise_file["mappings"]:
    ay = f"{m['surah_id']}:{m['ayah_from']}" + (f"-{m['ayah_to']}" if m['ayah_to'] != m['ayah_from'] else "")
    report += f"| `{m['event_id']}` | {m['review_status']} | {m['evidence_confidence']} | {ay} |\n"

report += """
---

## Events requiring scholarly review (`needs_precise_mapping`)

"""
for eid in sorted(needs_mapping):
    ev = next(x for x in events if x["id"] == eid)
    report += f"- `{eid}` — {ev['title_ar']} ({ev['node_id']})\n"

report += """
---

## Safe for public final display

Events that pass all gates: `review_status=approved`, valid `source_status`, `evidence_status=precise_evidence`, `evidence_confidence≠needs_review`.

"""
for e in safe_public:
    report += f"- `{e['id']}` — {e['title_ar']}\n"

if not safe_public:
    report += "- None yet beyond curated approved set above.\n"

REPORT_PATH.write_text(report, encoding="utf-8")

print("events:", before_count)
print("precise_evidence:", len([e for e in events if e.get("evidence_status") == "precise_evidence"]))
print("needs_precise_mapping:", len(needs_mapping))
print("downgraded:", len(set(downgraded)))
print("safe_public:", len(safe_public))
print("event_ayahs:", len(new_event_ayahs))
