import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const seedPath = process.argv[2] || join(root, 'src/data/seed_content.json');
const surahsPath = join(root, 'src/data/surahs.json');
const outDir = join(root, 'supabase/seed');
const outPath = join(outDir, '001_seed_content.sql');

const seed = JSON.parse(readFileSync(seedPath, 'utf8'));
const surahsFile = JSON.parse(readFileSync(surahsPath, 'utf8'));

/** @param {unknown} value */
function sqlLiteral(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
  if (typeof value === 'object') return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  return `'${String(value).replace(/'/g, "''")}'`;
}

const lines = [];
lines.push('-- Generated by scripts/export_seed_to_supabase_sql.mjs');
lines.push('-- Source: src/data/seed_content.json');
lines.push(`-- Generated at: ${new Date().toISOString()}`);
lines.push('-- NOTE: Does NOT include licensed full Quran ayah text.');
lines.push('BEGIN;');
lines.push('');

for (const src of seed.tafsir_sources || []) {
  lines.push(
    `INSERT INTO public.tafsir_sources (id, name_ar, author_ar, type, license_note, source_url, is_approved) VALUES (${sqlLiteral(src.id)}, ${sqlLiteral(src.name_ar)}, ${sqlLiteral(src.author_ar)}, ${sqlLiteral(src.type)}, ${sqlLiteral(src.license_note)}, ${sqlLiteral(src.source_url)}, ${sqlLiteral(src.is_approved)}) ON CONFLICT (id) DO UPDATE SET name_ar = EXCLUDED.name_ar, author_ar = EXCLUDED.author_ar, type = EXCLUDED.type, license_note = EXCLUDED.license_note, source_url = EXCLUDED.source_url, is_approved = EXCLUDED.is_approved, updated_at = now();`
  );
}
lines.push('');

for (const theme of seed.themes || []) {
  lines.push(
    `INSERT INTO public.themes (id, name_ar, description_ar, review_status, source_status) VALUES (${sqlLiteral(theme.id)}, ${sqlLiteral(theme.name_ar)}, ${sqlLiteral(theme.description_ar)}, ${sqlLiteral(theme.review_status || 'pending')}, ${sqlLiteral(theme.source_status || 'pending')}) ON CONFLICT (id) DO UPDATE SET name_ar = EXCLUDED.name_ar, description_ar = EXCLUDED.description_ar, review_status = EXCLUDED.review_status, source_status = EXCLUDED.source_status, updated_at = now();`
  );
}
lines.push('');

for (const node of seed.story_nodes || []) {
  lines.push(
    `INSERT INTO public.story_nodes (id, node_type, name_ar, name_en, short_title_ar, summary_ar, caution_note, is_sensitive, review_status, source_status, evidence_status, evidence_confidence, source_id, reviewer_note, network_conclusion_ar, network_conclusion_review_status, lessons_ar) VALUES (${sqlLiteral(node.id)}, ${sqlLiteral(node.node_type)}, ${sqlLiteral(node.name_ar)}, ${sqlLiteral(node.name_en)}, ${sqlLiteral(node.short_title_ar)}, ${sqlLiteral(node.summary_ar)}, ${sqlLiteral(node.caution_note)}, ${sqlLiteral(node.is_sensitive ?? false)}, ${sqlLiteral(node.review_status || 'pending')}, ${sqlLiteral(node.source_status || 'pending')}, ${sqlLiteral(node.evidence_status)}, ${sqlLiteral(node.evidence_confidence)}, ${sqlLiteral(node.source_id)}, ${sqlLiteral(node.reviewer_note)}, ${sqlLiteral(node.network_conclusion_ar)}, ${sqlLiteral(node.network_conclusion_review_status)}, ${sqlLiteral(node.lessons_ar || [])}) ON CONFLICT (id) DO UPDATE SET node_type = EXCLUDED.node_type, name_ar = EXCLUDED.name_ar, name_en = EXCLUDED.name_en, short_title_ar = EXCLUDED.short_title_ar, summary_ar = EXCLUDED.summary_ar, caution_note = EXCLUDED.caution_note, is_sensitive = EXCLUDED.is_sensitive, review_status = EXCLUDED.review_status, source_status = EXCLUDED.source_status, evidence_status = EXCLUDED.evidence_status, evidence_confidence = EXCLUDED.evidence_confidence, source_id = EXCLUDED.source_id, reviewer_note = EXCLUDED.reviewer_note, network_conclusion_ar = EXCLUDED.network_conclusion_ar, network_conclusion_review_status = EXCLUDED.network_conclusion_review_status, lessons_ar = EXCLUDED.lessons_ar, updated_at = now();`
  );
}
lines.push('');

for (const event of seed.story_events || []) {
  lines.push(
    `INSERT INTO public.story_events (id, node_id, title_ar, summary_ar, event_order, start_label_ar, end_label_ar, certainty_level, review_status, source_status, evidence_status, evidence_confidence, source_id, reviewer_note, theme_ids, lessons_ar, sources) VALUES (${sqlLiteral(event.id)}, ${sqlLiteral(event.node_id)}, ${sqlLiteral(event.title_ar)}, ${sqlLiteral(event.summary_ar)}, ${sqlLiteral(event.event_order)}, ${sqlLiteral(event.start_label_ar)}, ${sqlLiteral(event.end_label_ar)}, ${sqlLiteral(event.certainty_level || 'quran_explicit')}, ${sqlLiteral(event.review_status || 'pending')}, ${sqlLiteral(event.source_status || 'pending')}, ${sqlLiteral(event.evidence_status || 'needs_precise_mapping')}, ${sqlLiteral(event.evidence_confidence || 'needs_review')}, ${sqlLiteral(event.source_id)}, ${sqlLiteral(event.reviewer_note)}, ${sqlLiteral(event.theme_ids || [])}, ${sqlLiteral(event.lessons_ar || [])}, ${sqlLiteral(event.sources || [])}) ON CONFLICT (id) DO UPDATE SET node_id = EXCLUDED.node_id, title_ar = EXCLUDED.title_ar, summary_ar = EXCLUDED.summary_ar, event_order = EXCLUDED.event_order, start_label_ar = EXCLUDED.start_label_ar, end_label_ar = EXCLUDED.end_label_ar, certainty_level = EXCLUDED.certainty_level, review_status = EXCLUDED.review_status, source_status = EXCLUDED.source_status, evidence_status = EXCLUDED.evidence_status, evidence_confidence = EXCLUDED.evidence_confidence, source_id = EXCLUDED.source_id, reviewer_note = EXCLUDED.reviewer_note, theme_ids = EXCLUDED.theme_ids, lessons_ar = EXCLUDED.lessons_ar, sources = EXCLUDED.sources, updated_at = now();`
  );
}
lines.push('');

for (const ayah of seed.event_ayahs || []) {
  lines.push(
    `INSERT INTO public.event_ayahs (event_id, surah_id, ayah_from, ayah_to, ayah_key, relation_type, note_ar, evidence_note_ar, source_id, reviewer_note) VALUES (${sqlLiteral(ayah.event_id)}, ${sqlLiteral(ayah.surah_id)}, ${sqlLiteral(ayah.ayah_from)}, ${sqlLiteral(ayah.ayah_to)}, ${sqlLiteral(ayah.ayah_key)}, ${sqlLiteral(ayah.relation_type || 'main')}, ${sqlLiteral(ayah.note_ar || ayah.evidence_note_ar)}, ${sqlLiteral(ayah.evidence_note_ar || ayah.note_ar)}, ${sqlLiteral(ayah.source_id)}, ${sqlLiteral(ayah.reviewer_note)}) ON CONFLICT (event_id, surah_id, ayah_from, ayah_to) DO UPDATE SET ayah_key = EXCLUDED.ayah_key, relation_type = EXCLUDED.relation_type, note_ar = EXCLUDED.note_ar, evidence_note_ar = EXCLUDED.evidence_note_ar, source_id = EXCLUDED.source_id, reviewer_note = EXCLUDED.reviewer_note, updated_at = now();`
  );
}
lines.push('');

for (const link of seed.node_links || []) {
  lines.push(
    `INSERT INTO public.node_links (source_node_id, target_node_id, relation_type, evidence_note_ar, confidence, reviewer_note) VALUES (${sqlLiteral(link.source_node_id)}, ${sqlLiteral(link.target_node_id)}, ${sqlLiteral(link.relation_type)}, ${sqlLiteral(link.evidence_note_ar)}, ${sqlLiteral(link.confidence ?? 1)}, ${sqlLiteral(link.reviewer_note)}) ON CONFLICT (source_node_id, target_node_id, relation_type) DO UPDATE SET evidence_note_ar = EXCLUDED.evidence_note_ar, confidence = EXCLUDED.confidence, reviewer_note = EXCLUDED.reviewer_note, updated_at = now();`
  );
}
lines.push('');

for (const surah of surahsFile.surahs || []) {
  lines.push(
    `INSERT INTO public.surahs (id, name_ar, revelation_type, ayah_count, featured) VALUES (${sqlLiteral(surah.id)}, ${sqlLiteral(surah.name_ar)}, ${sqlLiteral(surah.revelation_type)}, ${sqlLiteral(surah.ayah_count)}, ${sqlLiteral(surah.featured ?? false)}) ON CONFLICT (id) DO UPDATE SET name_ar = EXCLUDED.name_ar, revelation_type = EXCLUDED.revelation_type, ayah_count = EXCLUDED.ayah_count, featured = EXCLUDED.featured, updated_at = now();`
  );
}

lines.push('');
lines.push('COMMIT;');
lines.push('');

mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, lines.join('\n'), 'utf8');

console.log('PASS export_seed_to_supabase_sql');
console.log(' input :', seedPath);
console.log(' output:', outPath);
console.log(' rows  :', {
  tafsir_sources: (seed.tafsir_sources || []).length,
  themes: (seed.themes || []).length,
  story_nodes: (seed.story_nodes || []).length,
  story_events: (seed.story_events || []).length,
  event_ayahs: (seed.event_ayahs || []).length,
  node_links: (seed.node_links || []).length,
  surahs: (surahsFile.surahs || []).length,
});
